### ISSUE TITLE
Able to remove items from trade gui

### ISSUE THREAD

**Issue by DrProfesor** [BtoBastian/SafeTrade#12]
I would recommend closing both players inventories before opening new ones. As players are able to remove items from the gui if they:
~Removed instructions~

Closing their inventories prior to opening new ones fixes this

**Comment by BtoBastian** [comment]
Hey,
thank you **very much** for pointing out this issue!
I'll fix it as soon as possible.
(I removed the instructions in order to prevent people from abusing the bug)

**Comment by BtoBastian** [comment]
The bug is fixed in 1.0.15.
Thank you again for reporting it!
