### ISSUE TITLE
Configurable Trading money amount

### ISSUE THREAD

**Issue by Portanna** [BtoBastian/SafeTrade#14]
Add in config the amount of default money added to the trade by clicking on the money item.

This way the plugin would suit every server's economy

**Comment by BtoBastian** [comment]
Hey,
this option already exists in the config. 
If your config does not have this option (because your config file was generated before I added it), just add it manually: https://github.com/BtoBastian/SafeTrade/blob/master/src/main/resources/config.yml

**Comment by Portanna** [comment]
Thanks dude
