### ISSUE TITLE
PlayerPickupItem WARN

### ISSUE THREAD

**Issue by andris155** [BtoBastian/SafeTrade#15]
`[00:29:40 WARN]: [SafeTrade] "SafeTrade v1.0.15" has registered a listener for org.bukkit.event.player.PlayerPickupItemEvent on method "public void de.oppermann.bastian.safetrade.listener.PlayerPickupItemListener.onPlayerPickupItem(org.bukkit.event.player.PlayerPickupItemEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [BtoBastian].`

**Comment by sgdc3** [comment]
The event got deprecated, will be fixed in the next version, in the meantime you can safely ignire such warning ;)

**Comment by BtoBastian** [comment]
Hey,
thank you for reporting.
Like sgdc3 said, this will be fixed in the next version.
