### ISSUE TITLE
Suggestion, allow increments of 1000 in money

### ISSUE THREAD

**Issue by TheZenKitteh** [BtoBastian/SafeTrade#18]
Large trades take a LONG time to get the money to the right amount. For example, a trade needing $100,000 takes a long time to get to. Incrementing by $1000 would make this process a lot easier for everyone involved.

**Comment by BtoBastian** [comment]
Hey,
you can change the values in the configuration file. (https://github.com/BtoBastian/SafeTrade/blob/master/src/main/resources/config.yml#L54-L56)
Is this what you need?

**Comment by TheZenKitteh** [comment]
That might work, thank you.
