### ISSUE TITLE
Custom Language with colors

### ISSUE THREAD

**Issue by PinoyLifeCraft** [BtoBastian/SafeTrade#2]
Hello Owner your plugin [ SafeTrade ] is indangered trade plugin and i want a customable lang. with color support

As I see on the auto gen lang. there are no color code if color code is available can you tell me the code [ & - § or what ever is that? ]

Please :disappointed: :+1:

**Comment by BtoBastian** [comment]
Hey,
sorry for the late response.
Colorcodes with § should work fine.
